// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type User = { username: string, password: string, uuid: string, pfp: string, email: string, bio: string, };